[package]
name = "opfp"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Core
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
futures.workspace = true
color-eyre.workspace = true
tracing-subscriber.workspace = true
byteorder.workspace = true

# CLI
clap.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-provider.workspace = true

# OP Types
fp-test-fixtures.workspace = true
kona-derive.workspace = true
kona-providers-alloy.workspace = true
kona-host.workspace = true
kona-genesis.workspace = true
kona-registry.workspace = true
kona-protocol.workspace = true

# OP Succinct
op-succinct-client-utils.workspace = true
op-succinct-host-utils.workspace = true
sp1-sdk.workspace = true
sp1-core-executor.workspace = true